### ISSUE TITLE
please add google maps again

### ISSUE THREAD

**Issue by aremai** [Eupeodes/gh#10]
hi,

please add the possbility to display the hashpoints on google maps again.
at the moment it's only possible to view them on bing  maps and openstreet maps.

thank you for all the great work and effort you put into geohashing.info :) top! :+1:

**Comment by Eupeodes** [comment]
To my regret that is the only thing of the old version that is hard or impossible to implement in the new version. Openlayers and google maps are not very compatible at the moment
