### ISSUE TITLE
SQL file error

### ISSUE THREAD

**Issue by zmbc** [Eupeodes/gh#12]
I just got geohashing.info running on my local machine. But in getting it to work I ran into an error with importing the SQL file.

The issue is this section:
`UNIQUE KEY `Index` (`date`)`
`UNIQUE KEY `url` (`url`(10))`

There's no comma at the end of the first line, and there isn't even a column called `url` in the `dow` table. Deleting the second line (`UNIQUE KEY `url` (`url`(10))`) completely fixed this without breaking anything that I've noticed.

The full error message when importing the SQL file:

```
Error

Static analysis:

4 errors were found during analysis.

    A comma or a closing bracket was expected. (near "UNIQUE KEY" at position 150)
    Unexpected beginning of statement. (near "`url`" at position 168)
    Unexpected beginning of statement. (near "10" at position 174)
    Unrecognized statement type. (near "ENGINE" at position 182)

SQL query:

CREATE TABLE `dow` ( `date` date NOT NULL, `dow` float(8,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (`date`), UNIQUE KEY `Index` (`date`) UNIQUE KEY `url` (`url`(10)) ) ENGINE=InnoDB DEFAULT CHARSET=utf8

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UNIQUE KEY `url` (`url`(10))
) ENGINE=InnoDB DEFAULT CHARSET=utf8' at line 6
```

**Comment by Eupeodes** [comment]
Thanks for the comment, the unique key for url was for the table page, somehow pasted it at the wrong place. That is always a risk when creating a file like this when the database already exists. Fixed it now.

**Comment by zmbc** [comment]
Thanks.
