### ISSUE TITLE
The "Map click / redetect action" is not saved with the settings

### ISSUE THREAD

**Issue by guillaumebrunerie** [Eupeodes/gh#16]
The "Map click / redetect action" (which can take any of four values, move home and/or center of grid) is not saved by the "Save my settings in a cookie" button, and always goes back to "Do nothing" when the page is reloaded.
This is not very convenient when one wants to often change graticule.

Thank you for the website which is quite useful and well-designed :)

**Comment by Kimpire** [comment]
I'd like to request the same fix, please :)

**Comment by ghost** [comment]
A setting that just puts all prefs into URL variables could be handy, then a bookmark would do the trick

**Comment by Eupeodes** [comment]
I totally overlooked this issue until today. I have now added the Map click / redetect action to the cookie. All prefs into an url is bit more challenging as that current way the url is used also includes the date, making it useless for daily checks.

**Comment by Kimpire** [comment]
The fix doesn't seem to have worked. In the Settings window, the Map click / redetect action is set to "nothing" no matter what option is selected.

**Comment by Eupeodes** [comment]
Can you try force refresh (usually Ctrl+f5). I just realized I forgot to update the version number meaning cached js files can still be used. I will update the version number when I'm at my desk (which will be in ~2 hours)

**Comment by Kimpire** [comment]
Aha! Force-refreshing worked. Thank you so much! :)

**Comment by Eupeodes** [comment]
Thanks for confirming it is a cache issue, I now have updated the version number so any cached js files are now fetched again with their new version
