### ISSUE TITLE
Option to draw rectangle and limit geohashes to those nearest my home.

### ISSUE THREAD

**Issue by b-jazz** [Eupeodes/gh#19]
I live near a corner of my quad (or whatever the official name is). More often than not, the geohash for the day in my quad is far, far away, while the geohash in the neighboring quad is right down the street. It would be nice to have a rectangle that is centered on the defined "home" drawn and only show geohashes which are "close" to me.

**Comment by ghost** [comment]
http://geohashing-shotgun.appspot.com has functionality to filter by a bounding box or radius within a given time span (like GH.info's one-week lookback tool but more general), but unfortunately relies on an unsupported Google Maps version as the basemap and is also subject to some showstopping bugs that result in returning the wrong hash location. It would be lovely if .info could take over some of those features.

**Comment by Eupeodes** [comment]
To overcome the issue of living in a corner of the graticule I always draw a 3x3 grid of hashes. If someone writes the code and sends a pull request I am certainly willing to look into it, however I don't see myself building this soon
