### ISSUE TITLE
Poster links are broken?

### ISSUE THREAD

**Issue by sporksmith** [Eupeodes/gh#31]
e.g. https://geo.crox.net/poster/2023-01-05_30_-97

I get a 404 response

**Comment by Eupeodes** [comment]
This seems to be a problem on the side of crox, this is not something I can fix from this repository. I have forwarded the error to crox and I am sure he will fix this is soon as he sees my message. I am closing this issue here.

**Comment by Eupeodes** [comment]
The links are to http (without the s), for geo.crox.net ssl is not enabled

**Comment by sporksmith** [comment]
Ah! Firefox these days does https-only, though I don't remember whether that's the default or I opted into it.
